[오버레이 / 오버레이 컨트롤러] 방송인 테이블 변경에 따른 수정
whileTrueDev/project-lc pull request #166
Opened 2021-12-20 08:19 UTC by leejineun

- userID 가져오던 부분 모두 email로 변경
- auth module 에러 수정
---
추가로 반드시 해야하는 사항
- s3 streamId별로 나눠진 디렉토리에서 이미지 가져오도록 변경

2021-12-21 03:46 UTC, hwasurr commented
liveShopping 모델과 LiveCommerceRanking 모델 간 관계성을 추가해주세요.
그리고 이름도 LiveShoppingRanking 으로 변경하는 게 좋아 보입니다.

2021-12-21 05:30 UTC, hwasurr approved these changes
dev 충돌 제거 하시면서 생긴 schema 오류 수정했습니다

2021-12-21 05:44 UTC, hwasurr requested changes

2021-12-21 05:44 UTC, hwasurr commented on libs/nest-modules/src/lib/overlay-controller/overlay-controller.service.ts
> +    const writePurchaseMessage = await this.prisma.liveShoppingPurchaseMessage.create({
uploadPurchase 함수에 liveshoppingId를 보내, 올바르게 적재되도록 구성해야 할 것 같습니다

2021-12-21 05:53 UTC, hwasurr commented
환경에 따른 올바른 위치로 요청할 수 있어야 할 것으로 보입니다.
localhost 로 명시하면 prod에서는 prod overlay-controller 서버로, dev에서는 dev overlay-controller 서버로 요청하게 되나요?

그게 아니라면 수정이 필요합니다

![스크린샷 2021-12-21 오후 2 52 30](https://user-images.githubusercontent.com/43170520/146878592-8ed09b77-33da-421d-a00e-3e0a5f5dbc03.png)

2021-12-21 05:56 UTC, leejineun commented on libs/nest-modules/src/lib/overlay-controller/overlay-controller.service.ts
> +    const writePurchaseMessage = await this.prisma.liveShoppingPurchaseMessage.create({
네 현재 해당 작업 진행중입니다

2021-12-21 09:13 UTC, leejineun commented on libs/nest-modules/src/lib/overlay-controller/overlay-controller.service.ts
> +    const writePurchaseMessage = await this.prisma.liveShoppingPurchaseMessage.create({
반영하였습니다

2021-12-22 00:05 UTC, hwasurr commented on libs/utils/src/lib/getHostUrl.ts
> +export const getOverlayControllerHost = (): string => {
동일한 환경변수 키 값을 가지도록 구성한 뒤, 환경에 따라 다른 값을 넣어주면 되므로, production, test 에서 동일한 키값을 조회하면 됩니다.

2021-12-22 00:05 UTC, hwasurr commented on libs/utils/src/lib/getHostUrl.ts
> +export const getOverlayControllerHost = (): string => {
0efbc8d 에서 수정하였습니다

2021-12-22 00:18 UTC, hwasurr approved these changes

2021-12-22 00:27 UTC, merged