feat : 크크쇼 판매자 메인페이지 디자인 적용
whileTrueDev/project-lc pull request #193
Opened 2022-01-13 05:26 UTC by jiyeon2

- 네비바
  - 로그인 했을 때 표시되는 알림버튼의 경우 팝오버 안에 넣지 못했음(알림버튼 눌렀을 때 이동할 페이지가 존재하지 않음)

- 절차 영역 - 방 송인 페이지에서 사용된 컴포넌트 동일하게 가져와 사용, 일부 수정함(모바일 사이즈일때)

2022-01-13 07:14 UTC, hwasurr reviewed
후기 이미지가 많이 깨지는 것으로 보이는데, 최대 크기를 조절하거나, 화질이 더 좋은 이미지로 교체할 수 있을까요?

2022-01-13 07:14 UTC, hwasurr commented on libs/components-seller/src/lib/SellerMainReviewSection.tsx
> +        <motion.div
강조 문구가 큰 화면에서 보여질 때 자글자글해보이네요 ㅜㅜ

2022-01-13 07:14 UTC, hwasurr commented on libs/components-seller/src/lib/SellerMainFeatureSection.tsx
> +export function SellerMainFeatureItem({ item }: { item: SectionData }): JSX.Element {
커서를 default로 고정하여 글씨위에 커서가 있어도 기본 커서가 보여지면 더 좋을 것 같습니다

2022-01-13 07:14 UTC, hwasurr commented on libs/components-shared/src/lib/MainProcessItemList.tsx
> +export function MainProcessItemList({
x 크기가 320 인 경우 > 표시로 인해 화면이 깨집니다.

또한 화면을 줄여 3 컬럼으로 표시될 때, 윗줄의 세번째 > 표시는 없는 것이 더 좋을 것 같습니다.

2022-01-13 07:14 UTC, hwasurr commented on libs/components-shared/src/lib/MainProcessItemList.tsx
> +export function MainProcessItemList({
base 에서는 2열, md에서는 3열, lg 이후는 6열로 구성해도 좋을 것 같습니다

2022-01-13 07:23 UTC, hwasurr commented on libs/components-shared/src/lib/Navbar.tsx
> +        <MenuItem my={1} icon={<SwitchIcon />} onClick={toggleColorMode}>
다크/라이트테마 변경시에는 메뉴화면이 꺼지지 않도록 구성할 수 있을까요?

2022-01-14 04:26 UTC, jiyeon2 commented on libs/components-seller/src/lib/SellerMainReviewSection.tsx
> +        <motion.div
후기이미지와 강조문구 이미지를 화질이 더 좋은 큰 이미지로 교체하였습니다!
큰화면에서 볼때 덜 자글자글하긴 한데
작은화면에서는 또 잘 안보이는거같네요..

2022-01-14 04:58 UTC, jiyeon2 commented on libs/components-shared/src/lib/Navbar.tsx
> +        <MenuItem my={1} icon={<SwitchIcon />} onClick={toggleColorMode}>
오 생각도 못했는데 테마 변경시 메뉴화면이 꺼지니까 불편하네요 수정하겠습니다

2022-01-14 05:02 UTC, jiyeon2 commented
코드리뷰 피드백 반영
- 후기, 강조구문 이미지 큰걸로 변경
- 후기 이미지 fadein 애니메이션 추가
- 이용방법 이미지 변경
- howToUse 부분 공통 컴포넌트로 만듦
- 특징아이템 커서 기본으로 설정
- process 부분 작은화면일 때 표시되는 이미지 개수 수정, `>` 표시 수정
- 테마변경 버튼 눌렀을 때 메뉴 꺼지지 않도록 수정

2022-01-17 00:17 UTC, hwasurr requested changes

2022-01-17 00:17 UTC, hwasurr commented on apps/web-seller/pages/_app.tsx
> +const theme = extendTheme({
`@project-lc/utils-frontend/createChakraTheme` 에 이미 적용되어 있습니다

2022-01-17 01:01 UTC, hwasurr approved these changes
수고많으셨습니다

2022-01-17 01:20 UTC, merged