feat : [방송인,판매자] 마이페이지 사이드바 및 레이아웃 구성
whileTrueDev/project-lc pull request #200
Opened 2022-01-18 01:44 UTC by jiyeon2

마이페이지 레이아웃 수정
- 데스크탑 화면일 경우
  - 사이드바 영역 추가
    - 사이드바 여닫는 버튼 추가
  - 사이드바 우측 영역 네비바, 푸터 고정
  - 사이드바 우측 가운데 컨텐츠 영역만 스크롤 가능
- 모바일 화면인 경우
  - 모바일 네비게이션(drawer)에 마이페이지 메뉴 버튼 추가
  - 모바일 화면인 경우에만 마이페이지 브레드크럼 네비게이션 표시

 기타 수정사항
 - 판매자센터 메인 후기 이미지 박스섀도우 적용
 
### 테스트케이스
    - [ ]  모바일 화면에서 마이페이지 네비게이션 메뉴가 drawer 형태의 사이드바 안에 표시된다
        - [ ]  탭 선택하면 해당 페이지로 이동하고 사이드바는 닫힌다
        - [ ]  모바일 화면에서 마이페이지 상단에 브레드크럼이 표시된다
    - [ ]  데스크탑 화면에서 마이페이지 네비게이션 메뉴는 열고 닫을 수 있는 사이드바에 표시된다
        - [ ]  사이드바가 닫혀있을 때 토글버튼은 왼쪽 상단에 있다
        - [ ]  사이드바가 열려있을때 토글버튼은 사이드바 내부 우측 상단에 있다
        - [ ]  데스크탑 화면에서 마이페이지 컨텐츠는 고정된 높이의 스크롤 가능한 영역에 표시된다
    - [ ]  현재 보고 있는 마이페이지 탭은 파란 배경색으로 표시된다
    - [ ]  판매자센터, 방송인센터에 따라 다른 마이페이지 탭 메뉴가 표시된다

2022-01-18 07:11 UTC, leejineun commented on libs/components-shared/src/lib/MypageLayout.tsx
> +            {isMobileSize && <MypageBreadcrumb />}
모바일에서만 사용가능하도록 변경하는 이유가 사이드 네비바와 기능 중복이라고 보신걸까요???

2022-01-18 07:30 UTC, jiyeon2 commented on libs/components-shared/src/lib/MypageLayout.tsx
> +            {isMobileSize && <MypageBreadcrumb />}
네~ 말씀하신대로 사이드바에도 동일한 네비게이션이 표시되어서 모바일 화면에서만 표시되게 해놨습니다
생각해보니 데스크탑 화면에서도 사이드바를 닫아두는 경우가 있어서 모든 화면에서 표시하는게 나을거같습니다!

2022-01-18 07:30 UTC, jiyeon2 commented on libs/components-shared/src/lib/MypageLayout.tsx
> +        <IconButton
해보겠습니다!!

2022-01-18 07:33 UTC, leejineun commented on libs/components-constants/src/lib/navigation.ts
> +  {
마이페이지, 크크마켓순은 어떨까요??

2022-01-18 07:43 UTC, jiyeon2 commented on libs/components-shared/src/lib/MypageLayout.tsx
> +        <IconButton
<img width="812" alt="스크린샷 2022-01-18 오후 4 42 02" src="https://user-images.githubusercontent.com/18395475/149892250-02a592a9-8576-4b68-b434-b12bdbba1d7d.png">
<img width="842" alt="스크린샷 2022-01-18 오후 4 42 33" src="https://user-images.githubusercontent.com/18395475/149892299-17a07da0-23b3-4d41-84b4-1b24f738c17b.png">

이러면 어떤가요??

2022-01-18 08:17 UTC, jiyeon2 commented on libs/components-constants/src/lib/navigation.ts
> +  {
원래 마이페이지, 크크마켓 순서였는데 제가 임의로 바꿨었습니다

모바일 화면에서 로그인했을 때
drawer 네비게이션에 마이페이지 메뉴도 같이 나타나도록 해놨습니다
<img width="371" alt="스크린샷 2022-01-18 오후 5 16 59" src="https://user-images.githubusercontent.com/18395475/149897586-7ba713a3-4e6e-4ed7-9b31-495e415c018d.png">

크크마켓, 마이페이지 이후에 마이페이지 메뉴가 나타나는게 자연스러워 보여서 순서를 바꿨었는데
데스크탑 화면에서는 마이페이지, 크크마켓 순으로 보이도록 하고
모바일 화면에서만 크크마켓, 마이페이지 순으로 보이게 수정하였습니다

2022-01-18 08:49 UTC, leejineun commented on libs/components-constants/src/lib/navigation.ts
> +  {
저도 뭐가 정확한 순서인지는 확신이 없는데, 크크마켓이 왼쪽에 있어서 뭔가 홈으로 이동될 것 같은 느낌에 클릭을 하게되는데, 갑자기 새 창이 뜨면 당황하게 되네요..

2022-01-19 02:18 UTC, leejineun commented on libs/components-shared/src/lib/MypageLayout.tsx
> +        <IconButton
접혔을 때 HamburgerIcon도 좋을 것 같습니다

2022-01-19 02:18 UTC, leejineun approved these changes

2022-01-19 02:51 UTC, hwasurr requested changes

2022-01-19 02:51 UTC, hwasurr commented on libs/components-shared/src/lib/MypageLayout.tsx
> +              md: `calc(100vh - ${NAVBAR_HEIGHT}px - ${FOOTER_HEIGHT}px)`,
footer를 고정시키니 매우 화면이 답답해 보입니다 mypage footer는 기본적으로 화면의 가장 아래에 붙어 있지만, 메인 패널이 화면 크기를 벗어나 스크롤이 생기는 경우에는 아래에 고정되어있기보다 메인패널의 하단에 붙어있는 방향성이 더 좋을 거라 생각됩니다

2022-01-19 02:51 UTC, hwasurr commented on libs/components-shared/src/lib/MypageLayout.tsx
> +        <DesktopMypageSidebar navLinks={navLinks} isOpen={isOpen} onToggle={onToggle} />
사이드바는 기본으로 열려있는 방향이 더 나아 보입니다

2022-01-19 02:51 UTC, hwasurr commented on libs/components-shared/src/lib/MypageLayout.tsx
> +        <DesktopMypageSidebar navLinks={navLinks} isOpen={isOpen} onToggle={onToggle} />
또한, `>>` , `<<` 표시가 너무 크며, 화면에 어울리지 않습니다

2022-01-19 02:51 UTC, hwasurr commented on libs/components-shared/src/lib/MypageLayout.tsx
> +        <DesktopMypageSidebar navLinks={navLinks} isOpen={isOpen} onToggle={onToggle} />
추가로 사이드바 선택 표시가 왼쪽으로 치우쳐 있습니다. (Text 컴포넌트에만 bg를 걸어둔 영향?)

2022-01-19 02:51 UTC, hwasurr commented on libs/components-shared/src/lib/MypageLayout.tsx
> +        <DesktopMypageSidebar navLinks={navLinks} isOpen={isOpen} onToggle={onToggle} />
마우스를 올렸을 때 underline 이 표시되는 것보다, 그냥 백그라운드 표시만 나타나는 게 더 적절해보입니다

2022-01-19 02:59 UTC, hwasurr commented on libs/components-shared/src/lib/Navbar.tsx
>            <Flex flex={{ base: 1 }} alignItems="center">
gap={2} 추가하는 것이 좋을 것 같습니다 로고와 버튼이 너무 붙어있게 보입니다

2022-01-19 05:08 UTC, jiyeon2 commented on libs/components-shared/src/lib/MypageLayout.tsx
> +        <DesktopMypageSidebar navLinks={navLinks} isOpen={isOpen} onToggle={onToggle} />
사이드바 토글 버튼의 경우 
음바쿠님도 닫혀있을때 햄버거 버튼이면 좋겠다고 하셔서 
모바일 네비게이션에서 사용하는 토글버튼과 동일한 컴포넌트(닫혀있을때 햄버거, 열려있을때는 x 아이콘)를 적용했습니다

사이드바 선택된 탭(파란배경)이 왼쪽으로 치우쳐 있는것을 전체 너비를 덮도록 수정했습니다~

2022-01-19 05:38 UTC, jiyeon2 commented on libs/components-shared/src/lib/MypageLayout.tsx
> +              md: `calc(100vh - ${NAVBAR_HEIGHT}px - ${FOOTER_HEIGHT}px)`,
메인패널 최소높이를 지정하여 푸터가 메인패널 하단에 항상 위치하도록 수정하였습니다~~

2022-01-20 07:04 UTC, hwasurr approved these changes
수고하셨습니다~

2022-01-20 07:08 UTC, merged