feat: 개인정보시스템 접근기록 로그 및 관리자 등급 추가
whileTrueDev/project-lc pull request #265
Opened 2022-03-04 01:24 UTC by leejineun

- [x]  관리자 계정 등급 추가
  - super 계정 : 다른 계정 등급 관리 및 개인정보 접근 가능
  - full 계정  : 개인정보 접근 가능
  - normal : 개인정보 접근 불가능
- [x]  권한 없는 계정 접근 불가 페이지
  - 판매자-계좌정보목록
  - 판매자-사업자등록정보검수
  - 방송인-정산정보검수
- [x]  개인정보 접근 로그 기능 추가
  - 접근 Email
  - ip
  - 접근일자
  - 접근한 정보의 페이지 또는 종류
  - 접근한 정보의 처리 유형 (view, download)
- [x] 관리자 페이지 비밀번호 제약 10자리 이상으로 변경
- [x] super계정이 다른 계정의 권한 변경 로그 기능 추가

2022-03-04 02:10 UTC, leejineun commented
production 배포시, production db 직접 접근을 통해 개인정보처리 담당자 계정만 super로 변경 필요합니다.

2022-03-07 08:51 UTC, hwasurr commented
> production 배포시, production db 직접 접근을 통해 개인정보처리 담당자 계정만 super로 변경 필요합니다.

마이그레이션 파일에 insert 또는 update 쿼리를 작성해 해당 작업을 진행할 수 있습니다

2022-03-08 02:24 UTC, jiyeon2 commented on apps/admin/pages/seller/account.tsx
> +  const { mutateAsync } = useAdminPrivacyApproachHistoryMutation();
이 과정이 다른 컴포넌트에서도 사용되니 훅으로 분리해도 좋을거같아요 
이런식으로 하면 어떨까요..???
```ts
export function useAdminApproachHistory(dto: PrivacyApproachHistoryDto): void {
  const { mutateAsync } = useAdminPrivacyApproachHistoryMutation();
  const { data: profile, isLoading } = useProfile();
  const router = useRouter();
  const toast = useToast();

  if (!isLoading && !['super', 'full'].includes(profile.adminClass)) {
    toast({
      title: '권한없는 계정',
      status: 'error',
    });
    router.push('/admin');
  }
  console.log(dto);

  useEffect(() => {
    if (!isLoading && ['super', 'full'].includes(profile.adminClass)) {
      mutateAsync(dto);
    }
  }, []);
}

// SettlementInfo 컴포넌트에서 
function SettlementInfo({ propname }: SettlementInfoProps): JSX.Element {
  useAdminApproachHistory({
    infoType: 'broadcasterSettlementAccount',
    actionType: 'view',
  });
  
  return (<...>)
```

2022-03-08 02:49 UTC, jiyeon2 approved these changes

2022-03-08 03:33 UTC, hwasurr requested changes

2022-03-08 03:33 UTC, hwasurr commented on libs/prisma-orm/prisma/migrations/20220303084934_/migration.sql
> +) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
> production 배포시, production db 직접 접근을 통해 개인정보처리 담당자 계정만 super로 변경 필요합니다.


특정 관리자를 슈퍼관리자로 지정하는 UPDATE 쿼리를 여기서 작성해 주시면 됩니다. (필요하다면 admin class 변경 내역을 남기는 INSERT 쿼리도 여기서 작성하실 수 있습니다.)

2022-03-10 06:31 UTC, leejineun commented on apps/admin/pages/seller/account.tsx
> +  const { mutateAsync } = useAdminPrivacyApproachHistoryMutation();
해당 부분 수정하였습니다.

2022-03-10 06:31 UTC, leejineun commented on libs/prisma-orm/prisma/migrations/20220303084934_/migration.sql
> +) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
해당 쿼리 추가하였습니다.

2022-03-10 06:45 UTC, hwasurr approved these changes

2022-03-11 06:54 UTC, merged