feat: 관리자 - 쿠폰관리
whileTrueDev/project-lc pull request #383
Opened 2022-06-02 08:37 UTC by leejineun

- [x] 쿠폰생성
  - [x ] 쿠폰생성 버튼
  - [x ] 쿠폰이름
  - [x ] 할인방법
  - [x ] 할인액
  - [x ] 할인영역
  - [x ] 할인상품 선택
  - [x ] 시작날짜
  - [x ] 종료날짜
  - [x ] 최대할인금액
  - [x ] 최소주문액
  - [x ] 메모
  - [x ] 제외하거나 지정할 상품 선택
- [x ] 쿠폰 리스트
  - [x ] 상세보기 버튼
    - 쿠폰 정보 및 연결된 상품 확인 가능
  - [x ] 관리 버튼
    - 관리 페이지로 이동
  - [x ] 삭제버튼
- [x ] 관리페이지
  - [x ] 쿠폰 발행된 소비자 목록
  - [x ] 쿠폰을 발행할 소비자 목록
  - [x ] 일괄발급
  - [x ] 개별발급
  - [x ] 삭제
  - [x ] 개별 쿠폰 상태 수정
- [x ] 쿠폰 로그 보기
  - 쿠폰 로그 확인가능

2022-06-03 01:47 UTC, jiyeon2 commented on libs/hooks/src/lib/queries/useAdminCustomerCoupon.tsx
> +    'AdminCustomerCoupon',
`['AdminCustomerCoupon, dto]` 등  쿠폰번호나 소비자별로 쿼리데이터를 구분할 수 있도록 쿼리키를 수정해야 할듯합니다

모든 쿠폰관리페이지에서 동일한 쿼리키 'AdminCustomerCoupon'를 사용하고 있어서 coupon/2 페이지로 들어갔는데 coupon/1의 발행목록이 뜨는 현상이 발생합니다

2022-06-03 01:51 UTC, jiyeon2 commented on libs/nest-modules-admin/src/admin/admin-coupon.controller.ts
> +  async createCoupon(@Body() dto: CouponDto): Promise<Coupon> {
ValidationPipe를 삭제하신 이유가 궁금합니다 오류가 발생하나요??

2022-06-03 02:08 UTC, jiyeon2 requested changes
쿠폰관리페이지에서 해당 쿠폰과 관련없는 쿠폰발행목록이 표시되는 현상이 있습니다 확인 부탁드립니다!

2022-06-03 07:03 UTC, leejineun commented on libs/nest-modules-admin/src/admin/admin-coupon.controller.ts
> +  async createCoupon(@Body() dto: CouponDto): Promise<Coupon> {
개발 중에 자꾸 에러나서 없애뒀다가 나중에 수정하려고 했는데, 그대로 올라갔네요 ㅜㅜ 해당 부분 수정하였습니다.

2022-06-03 07:31 UTC, hwasurr approved these changes
수고하셨습니다 간단한 수정사항 적용하였습니다 확인해주시기 바랍니다 810b581

2022-06-07 00:11 UTC, jiyeon2 approved these changes
고생하셨습니다~

2022-06-07 00:34 UTC, merged