[크크쇼] 수정 - 가상계좌결제 후 환불처리, 가상계좌번호 저장, 주문목록에서 주문취소버튼
whileTrueDev/project-lc pull request #429
Opened 2022-07-01 03:03 UTC by jiyeon2

수정내역
- 가상계좌결제한 주문에 반품요청시 결제취소와 동일한 형태의 환불계좌정보 입력폼 적용
- 가상계좌결제 주문에 대한 결제취소시 발생한 에러 수정
- 가상계좌결제 주문 상세페이지에서 가상계좌 안뜨는 문제 수정
- 환불처리되어 '결제취소' 상태가 된 주문에 주문취소 버튼이 뜨는 문제 수정

2022-07-01 04:38 UTC, hwasurr approved these changes
수고하셨습니다

2022-07-01 04:38 UTC, hwasurr commented on libs/components-web-kkshow/src/lib/mypage/orderList/OrderCancelDialog.tsx
> +  } = useFormContext();
`RefundAccountDto` 제너릭타입을 삭제하신 이유가 있나요?

2022-07-01 04:48 UTC, jiyeon2 commented on libs/components-web-kkshow/src/lib/mypage/orderList/OrderCancelDialog.tsx
> +  } = useFormContext();
<RefundAccountForm> 컴포넌트를 다른곳(환불요청생성하는 부분)에서도  사용하려고 삭제하였습니다
환불요청생성에서는 ExchangeReturnFormData 라는 별도의 타입을 사용하고 있습니다
FormContext의 타입을 알 수 없어 좋은 방법은 아니네요..

2022-07-01 04:59 UTC, hwasurr commented on libs/components-web-kkshow/src/lib/mypage/orderList/OrderCancelDialog.tsx
> +  } = useFormContext();
공통되는 필드가 있어 사용하시는거라면 공통필드를 따로 클래스로 구성하시고,
각 dto 클래스가 공통클래스를 상속받는 방식으로 구성하시면 좋을 것 같습니다

2022-07-01 06:54 UTC, hwasurr requested changes

2022-07-01 06:54 UTC, hwasurr commented on libs/nest-modules-payment/src/lib/payment.service.ts
> +        account: result.virtualAccount?.accountNumber,
해당 필드에 대해 암호화처리 추가 및 은행이름 추가를 진행해야 할 것으로 보입니다

2022-07-01 06:59 UTC, hwasurr commented on libs/nest-modules-payment/src/lib/payment.service.ts
> +        account: result.virtualAccount?.accountNumber,
제가 진행해 이 브랜치에 병합하도록 하겠습니다~

2022-07-01 06:59 UTC, hwasurr commented on libs/nest-modules-payment/src/lib/payment.service.ts
> +        account: result.virtualAccount?.accountNumber,
제가 진행해 이 브랜치에 병합하도록 하겠습니다~

2022-07-04 04:31 UTC, hwasurr approved these changes

2022-07-04 07:42 UTC, jiyeon2 commented on libs/components-web-kkshow/src/lib/mypage/orderList/OrderCancelDialog.tsx
> +  } = useFormContext();
RefundAccountDto 를 생성하여 <RefundAccountForm> 컴포넌트에도 적용하고, 
해당 필드가 필요한 CreateReturnDto, CreateRefundDto 등에서 상속하도록 하였습니다

2022-07-04 07:57 UTC, hwasurr approved these changes
수고하셨습니다

2022-07-04 07:57 UTC, merged