[크크쇼-방송인 홍보페이지] 신규기능: 랭킹
whileTrueDev/project-lc pull request #531
Opened 2022-08-30 08:54 UTC by hwasurr

# 할일

- [x]  랭킹 컴포넌트 구성
- [x]  방송인 홍보페이지 레이아웃변경
    - [x]  아직 구매자 없는 경우 어떻게 처리할 지
        - ~~아예 랭킹목록이 보여지지 않는다~~
        - 랭킹목록이 보여지되 비어있다 or 비어있다는 문구가 표시된다
    - ~~레이아웃 - 위에서 아래로 라이브중인상품 - 랭킹 - 상품홍보중인 상품~~
- [x]  랭킹 정보 조회
    - [x]  구매금액
    - [x]  선물금액
    - [x]  리뷰개수

# 테스트케이스

- [ ]  랭킹을 올바르게 확인할 수 있다 (화면 별)
    - [ ]  모바일
    - [ ]  PC
- [ ]  랭킹을 올바르게 확인할 수 있다 (타입 별)
    - [ ]  구매금액
    - [ ]  선물금액
    - [ ]  리뷰개수

2022-09-01 07:53 UTC, jiyeon2 commented on libs/nest-modules-broadcaster/src/broadcaster/broadcaster-promotion-page.service.ts
> +        giftFlag: dto.by === GetRankingBy.giftPrice,
제가 보기에 구매금액 기준으로 조회하는 경우 선물주문금액이 빠지게 되는게 이상해보여서요 
누적 주문 금액의 기준이 선물주문을 제외한 주문 금액의 합이 맞나요??

2022-09-02 02:19 UTC, jiyeon2 commented on libs/nest-modules-broadcaster/src/broadcaster/broadcaster-promotion-page.service.ts
> +      return result;
여기도 똑같이 `return result
        .sort((a, b) => b._count - a._count) // 내림차순 정렬
        .slice(0, dto.take || 5);`
        정렬하고 5개로 잘라야 할듯합니다!

2022-09-02 02:24 UTC, jiyeon2 requested changes
리뷰 개수로 랭킹 데이터 구하는 부분 확인 부탁드립니다!

2022-09-02 06:24 UTC, hwasurr commented on libs/nest-modules-broadcaster/src/broadcaster/broadcaster-promotion-page.service.ts
> +        giftFlag: dto.by === GetRankingBy.giftPrice,
포함하도록 수정하였습니다.

2022-09-02 06:26 UTC, jiyeon2 approved these changes
👍

2022-09-02 07:17 UTC, merged