[기능 추가] 라이브 쇼핑 등록 기능
whileTrueDev/project-lc pull request #64
Opened 2021-10-13 06:00 UTC by leejineun

[x] 승인된 상품 입력창 AutoComplete
[x] 담당자 연락처
  - 기존 연락처 사용
  - 새 연락처 등록 가능
  - 새 연락처를 기본 연락처로 등록 가능
[x] 요청사항 등록 가능

2021-10-13 09:40 UTC, jiyeon2 requested changes

2021-10-13 09:40 UTC, jiyeon2 commented on libs/components/src/lib/LiveShoppingRegistManagerContacts.tsx
> +                {...register('email', { required: '이메일을 작성해주세요.' })}
회원가입 할 때 사용한 이메일용 register 옵션 작성해 둔 게 있어요!

`import { emailRegisterOptions} from '@project-lc/shared-types';`

emailRegisterOptions확인해보시고 괜찮으시면 이거 적용해도 좋을거같아요

2021-10-13 09:40 UTC, jiyeon2 commented on libs/nest-modules/src/lib/seller/seller.service.ts
> +        seller: { connect: { id: userId.id } },
`seller: { connect: { email: sellerEmail } },` 해도 seller랑 연결돼요! 
셀러 정보가 필요한 경우가 아니면 따로 userId 구하는 코드는 안 쓰셔도 될거같아요

2021-10-13 09:40 UTC, jiyeon2 commented on libs/shared-types/src/lib/dto/sellerContacts.dto.ts
> +export type SellerContactsDTOWithoutIdDTO = SubPartial<SellerContactsDTO, 'id'>;
지금 타입스크립트 버전에서는 Omit 타입이 기본으로 존재하는 걸로 알고있습니다 
`SellerContactsDTOWithoutIdDTO = Omit<SellerContactsDTO, 'id'>` 로 사용하면 될거같은데
따로 Omit이랑 SubPartial 선언해서 사용하신 이유가 궁금합니다!

2021-10-13 09:40 UTC, jiyeon2 commented on libs/components/src/lib/LiveShoppingRegistManagerContacts.tsx
> +  } = useFormContext<UseFormContext>();
따로 UseFormContext 안만들고 LiveShoppingRegistForm 파일에 있는 UseForm 인터페이스 가져다 쓰셔도 될거같아요~

2021-10-13 09:40 UTC, jiyeon2 commented on libs/hooks/src/lib/mutation/useCreateSellerContacts.tsx
> +export type SellerContactsDTOWithoutIdDTO = SubPartial<SellerContactsDTO, 'id'>;
sellerContacts.dto.ts 랑 중복되어 있어요 
나중에 헷갈릴 수도 있으니 한쪽에서 가져와서 사용하는 게 좋을듯합니다!

2021-10-13 09:40 UTC, jiyeon2 commented on libs/hooks/src/lib/mutation/useCreateShippingGroup.tsx
> +export type useCreateShippingGroupRes = SellerContacts;
SellerContacts 랑 배송비그룹은 관련 없는거같은데 바꾸신 이유가 있으신가요...???

2021-10-14 00:37 UTC, leejineun commented on libs/components/src/lib/LiveShoppingRegistForm.tsx
> +  const { handleSubmit } = methods;
아 중복코드였군요 말씀대로 반영하였습니다

2021-10-14 02:14 UTC, leejineun commented on libs/components/src/lib/LiveShoppingRegistManagerContacts.tsx
> +  } = useFormContext<UseFormContext>();
넵 반영하였습니다

2021-10-14 02:26 UTC, jiyeon2 approved these changes
고생하셨습니다!! 👍

2021-10-15 00:54 UTC, chanuuuuu commented on libs/components/src/lib/LiveShoppingRegistRequestField.tsx
> +          placeholder={`[예시]
작은 모니터 화면으로 보니까 의도했던 예시형태가 아니었습니다.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/42171155/137415188-89e7ad93-4807-4d12-bdf1-332f5f52fce3.png">

2021-10-15 00:56 UTC, chanuuuuu commented on libs/components/src/lib/LiveShoppingRegistManagerContacts.tsx
> +                      required: "'-'을 제외하고 숫자만 입력하세요.",
전화번호의 입력폼이 기본적으로 -이 명시되어있기 떄문에 "'-'을 제외하고 숫자만 입력하세요." 의 텍스트는 사용하지 않거나 수정해면 될 것 같습니다.

2021-10-15 00:57 UTC, chanuuuuu commented on libs/components/src/lib/LiveShoppingRegistManagerContacts.tsx
> +                id="email"
이메일의 입력의 경우, 올바르지 않은 입력의 형태는 react-hook-form의 에러가 아닌 HTML 태그의 에러형태로 표현됩니다. 통일성을 위해서 HTML 태그의 에러형태가 아닌  react-hook-form의 에러메세지를 통해 표현될 수 있도록 변경해야합니다. ~(사실 저도 그렇게 변경하였습니다.)~

2021-10-15 01:40 UTC, leejineun commented on libs/components/src/lib/LiveShoppingRegistRequestField.tsx
> +          placeholder={`[예시]
모니터 해상도 알 수 있을까요? 제 컴퓨터에선 아무리 줄이고 확대해도 똑같이 재현이 안되네요..

2021-10-15 01:40 UTC, leejineun commented on libs/components/src/lib/LiveShoppingRegistManagerContacts.tsx
> +                id="email"
type="email" 삭제 처리하였습니다

2021-10-15 01:40 UTC, leejineun commented on libs/components/src/lib/LiveShoppingRegistManagerContacts.tsx
> +                      required: "'-'을 제외하고 숫자만 입력하세요.",
넵 수정했습니다

2021-10-15 02:08 UTC, chanuuuuu commented on libs/components/src/lib/LiveShoppingRegistRequestField.tsx
> +          placeholder={`[예시]
13.3인치 2560 × 1600인데 특수한 경우라고 한다면 수정하지 않아도 될 것 같습니다.

2021-10-15 04:32 UTC, hwasurr commented on libs/components/src/lib/LiveShoppingRegistForm.tsx
> +                data={contacts.data}
#69 에서 수정함

2021-10-15 04:40 UTC, hwasurr requested changes

2021-10-15 04:40 UTC, hwasurr commented on libs/nest-modules/src/lib/live-shopping/live-shopping.controller.ts
> +  async getApprovedGoodsList(
`GET /live` 엔드포인트만으로는 연결된 상품이 반환될거라고는 상상할 수 없습니다. 엔드포인트명을 더 명확히 작성해주세요

- `/live/available-goods`
- `/live/goods/avilable`
- `/live/approved-goods`
- `/live/goods/approved`
- `/live/confirmed-goods`
- `/live/goods/confirmed`

2021-10-15 04:40 UTC, hwasurr commented on libs/nest-modules/src/lib/live-shopping/live-shopping.controller.ts
> +@Controller('live')
live 는 의미가 모호합니다.
live-shopping으로 변경하는 것이 바람직해 보입니다.

2021-10-15 04:40 UTC, hwasurr commented on libs/nest-modules/src/lib/live-shopping/live-shopping.controller.ts
> +  @Post('/create')
`POST /live-shopping` 으로는 POST 요청임을 통해 라이브쇼핑이 생성된다는 의미를 곧바로 유추할 수 있으므로 /create 부분은 삭제하시기 바랍니다.

2021-10-15 04:40 UTC, hwasurr commented on libs/nest-modules/src/lib/seller/seller.controller.ts
> +  @Post('contacts-create')
POST /seller/contracts 만으로 연락처 생성에 대한 의미를 유추할 수 있습니다 (POST 가 생성의 의미를 가지므로)

contacts-create => contacts로 변경해주세요

2021-10-15 04:40 UTC, hwasurr commented on libs/shared-types/src/lib/res-types/goodsList.res.ts
> +export type ApprovedGoodsNameAndIds = {
ApprovedGoodsNameAndIds 는 복수형입니다

`ApprovedGoodsNameAndId` 로 반환하시고
`ApprovedGoodsNameAndId[]` 외 같이 사용하거나

```ts
type ApprovedGoodsNameAndIds = ApprovedGoodsNameAndId[];
```

와 같이 정의해 사용하는 것이 좋아보입니다

2021-10-15 07:25 UTC, leejineun commented on libs/hooks/src/lib/mutation/useCreateLiveShopping.tsx
> +export const useCreateLiveShopping = (): UseMutationResult<
네 반영하였습니다

2021-10-15 07:26 UTC, leejineun commented on libs/components/src/lib/LiveShoppingRegistForm.tsx
> +                data={contacts.data}
네 내용 확인하였습니다.

2021-10-15 07:37 UTC, leejineun commented on libs/nest-modules/src/lib/live-shopping/live-shopping.controller.ts
> +@Controller('live')
네 반영하였습니다

2021-10-15 07:38 UTC, leejineun commented on libs/nest-modules/src/lib/live-shopping/live-shopping.controller.ts
> +  @Post('/create')
네 반영하였습니다

2021-10-15 07:40 UTC, leejineun commented on libs/nest-modules/src/lib/seller/seller.controller.ts
> +  @Post('contacts-create')
네 변경하였습니다

2021-10-15 07:50 UTC, leejineun commented on libs/hooks/src/lib/mutation/useCreateSellerContacts.tsx
> +export const useCreateSellerContacts = (): UseMutationResult<
네 반영하였습니다

2021-10-15 07:50 UTC, leejineun commented on libs/nest-modules/src/lib/live-shopping/live-shopping.controller.ts
> +  async getApprovedGoodsList(
반영하였습니다

2021-10-15 07:50 UTC, leejineun commented on libs/shared-types/src/lib/res-types/goodsList.res.ts
> +export type ApprovedGoodsNameAndIds = {
넵 변경하였습니다

2021-10-15 08:27 UTC, merged